package main

import (
	"context"
	"net/http"
	"reflect"
	"testing"

	"github.com/mark3labs/mcp-go/mcp"
)

func TestForwardedHeadersPassesEverythingButHopByHop(t *testing.T) {
	h := http.Header{}
	h.Set("Authorization", "Bearer secret")
	h.Set("Cookie", "a=1")
	h.Set("X-Repo-Root", "/srv/app")
	h.Set("User-Agent", "claude")
	// hop-by-hop / framing — must be dropped (regenerated by the wire layer).
	h.Set("Connection", "keep-alive")
	h.Set("Keep-Alive", "timeout=5")
	h.Set("Transfer-Encoding", "chunked")
	h.Set("Host", "evil.example")
	h.Set("Content-Length", "999")
	h.Set("Upgrade", "websocket")
	h.Set("Proxy-Authorization", "Basic xxx")
	h.Set("Te", "trailers")
	h.Set("Trailer", "X-Foo")

	ctx := withClientHeaders(context.Background(), &http.Request{Header: h})
	got := forwardedHeaders(ctx)

	want := map[string]string{
		"Authorization": "Bearer secret",
		"Cookie":        "a=1",
		"X-Repo-Root":   "/srv/app",
		"User-Agent":    "claude",
	}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("forwardedHeaders mismatch:\n got=%#v\nwant=%#v", got, want)
	}
}

func TestForwardedHeadersJoinsMultiValue(t *testing.T) {
	h := http.Header{}
	h.Add("X-Multi", "one")
	h.Add("X-Multi", "two")
	ctx := withClientHeaders(context.Background(), &http.Request{Header: h})
	if got := forwardedHeaders(ctx)["X-Multi"]; got != "one, two" {
		t.Fatalf("multi-value join = %q, want %q", got, "one, two")
	}
}

func TestForwardedHeadersNilWhenAbsent(t *testing.T) {
	if got := forwardedHeaders(context.Background()); got != nil {
		t.Fatalf("no stashed headers should yield nil, got %#v", got)
	}
	// Only hop-by-hop present → nothing to forward → nil.
	h := http.Header{}
	h.Set("Connection", "close")
	ctx := withClientHeaders(context.Background(), &http.Request{Header: h})
	if got := forwardedHeaders(ctx); got != nil {
		t.Fatalf("only hop-by-hop should yield nil, got %#v", got)
	}
}

func TestNotificationParamsMergesMetaAndFields(t *testing.T) {
	n := mcp.JSONRPCNotification{}
	n.Params.AdditionalFields = map[string]any{"progress": 0.5, "progressToken": "tok"}
	n.Params.Meta = map[string]any{"trace": "abc"}

	got := notificationParams(n)
	if got["progress"] != 0.5 || got["progressToken"] != "tok" {
		t.Fatalf("additional fields not preserved: %#v", got)
	}
	meta, ok := got["_meta"].(map[string]any)
	if !ok || meta["trace"] != "abc" {
		t.Fatalf("_meta not preserved: %#v", got)
	}
}

func TestNotificationParamsNilWhenEmpty(t *testing.T) {
	if got := notificationParams(mcp.JSONRPCNotification{}); got != nil {
		t.Fatalf("empty notification should yield nil params, got %#v", got)
	}
}
